name: Build
on:
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: git switch
        run: |
          git config user.name actions
          git config user.email actions@mewl.me
          git fetch
          git switch dist
      - name: Merge
        run: git merge origin/master --no-commit --no-ff
      - name: Install deps
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Commit
        run: |
          git add dist/*
          git commit -m "Merge master"
      - name: Push
        run: git push
